# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sailhouse < Formula
  desc ""
  homepage "https://sailhouse.dev"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sailhouse/cli/releases/download/v0.1.1/sailhouse_Darwin_x86_64.tar.gz"
      sha256 "7883f836acde69beeb8b147c83a6ee3bd85ba025c225cee64ceecf9c6869ee51"

      def install
        bin.install "sailhouse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sailhouse/cli/releases/download/v0.1.1/sailhouse_Darwin_arm64.tar.gz"
      sha256 "aba41d3c60ea490e4aa54ceb80c4da0573ddbdc18cf64b14280dee7e5f673d62"

      def install
        bin.install "sailhouse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sailhouse/cli/releases/download/v0.1.1/sailhouse_Linux_arm64.tar.gz"
      sha256 "a8b09c0816bac72e4e4a2ae7ceba5aa414f2cab444e28c806c54212f82bbe86c"

      def install
        bin.install "sailhouse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sailhouse/cli/releases/download/v0.1.1/sailhouse_Linux_x86_64.tar.gz"
      sha256 "bde77490562ef8dc20d6093513402b2a0331e035a0e9e6e462bdb14ee9b9aa1d"

      def install
        bin.install "sailhouse"
      end
    end
  end
end
