# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sailhouse < Formula
  desc ""
  homepage "https://sailhouse.dev"
  version "0.4.1"

  on_macos do
    on_intel do
      url "https://github.com/sailhouse/cli/releases/download/v0.4.1/sailhouse_Darwin_x86_64.tar.gz"
      sha256 "5ccbf00d5989a93e77b4eee91b319358a301640d4109d530dcb14066d2195e66"

      def install
        bin.install "sailhouse"
      end
    end
    on_arm do
      url "https://github.com/sailhouse/cli/releases/download/v0.4.1/sailhouse_Darwin_arm64.tar.gz"
      sha256 "c53cb4e6c0afbb7b356af93902af029a15566d9faafedda43d4488c31a71f2a7"

      def install
        bin.install "sailhouse"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sailhouse/cli/releases/download/v0.4.1/sailhouse_Linux_x86_64.tar.gz"
        sha256 "d9abaebd101325129581ee43de1baaffdaa7edf10507b6befecb13545774bd0c"

        def install
          bin.install "sailhouse"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sailhouse/cli/releases/download/v0.4.1/sailhouse_Linux_arm64.tar.gz"
        sha256 "5fb12fcbdd509c66432761f66293627879f0ac9ab51e5267d234a6c89a3cdd56"

        def install
          bin.install "sailhouse"
        end
      end
    end
  end
end
