# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sailhouse < Formula
  desc ""
  homepage "https://sailhouse.dev"
  version "0.2.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sailhouse/cli/releases/download/v0.2.8/sailhouse_Darwin_arm64.tar.gz"
      sha256 "4a41c67e5d05332dd0750ae6e03e61e6052abf447beb28a2e3d675545171539a"

      def install
        bin.install "sailhouse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sailhouse/cli/releases/download/v0.2.8/sailhouse_Darwin_x86_64.tar.gz"
      sha256 "da1e035ed6bd7e15e28bc17b80eed14b35f73d7f701cb2d8df81a99eda39a4c4"

      def install
        bin.install "sailhouse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sailhouse/cli/releases/download/v0.2.8/sailhouse_Linux_arm64.tar.gz"
      sha256 "d2288eadac44f0ef63e65fe8c5319157524afc240020b8bd1dfe731b81162e21"

      def install
        bin.install "sailhouse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sailhouse/cli/releases/download/v0.2.8/sailhouse_Linux_x86_64.tar.gz"
      sha256 "7ee7ec1841a6536f3071a793955aa4e316c45bbdb2e0d1fb91c77f7de50db4e3"

      def install
        bin.install "sailhouse"
      end
    end
  end
end
